- name: Download Agent file
  get_url:
    url: "https://github.com/grafana/agent/releases/{{ agent_version_url }}/agent-linux-{{ type[ansible_architecture] }}.zip"
    dest: "/tmp/agent-linux.zip"
    mode: '0644'

- name: Unarchive Agent
  unarchive:
    src: "/tmp/agent-linux.zip"
    dest: "{{ agent_location }}"
    remote_src: yes
    mode: '0755'

- name: Create directory for Agent's config file
  file:
    state: directory
    recurse: yes
    path: "{{ config_location }}"
    mode: 0755

- name: Create Agent's config file
  template:
    src: agent-config.yaml.j2
    dest: "{{ config_location }}/agent-config.yaml"
    mode: 0644
    force: yes

- name: Create Grafana Agent's Supervisor config file
  template:
    src: grafana-agent.conf.j2
    dest: "/etc/supervisor/conf.d/grafana.conf"
    mode: 0644
    force: yes

- name: Start Supervisord
  service:
    name: supervisor
    state: started

- name: Reread Supervisor configuration
  supervisorctl:
    name: grafana-agent
    state: present

- name: Restart grafana-agent service
  supervisorctl:
    name: grafana-agent
    state: restarted

- name: Install Promtail
  include_tasks: "promtail.yml"
  when:
    - loki_user is defined
