- name: Download latest Promtail release
  get_url:
    url: "https://github.com/grafana/loki/releases/latest/download/promtail-linux-{{ promtail_type[ansible_architecture] }}.zip"
    dest: "/tmp/promtail-linux.zip"
    mode: '0644'

- name: Create directory for Promtail's files
  file:
    state: directory
    recurse: yes
    path: "{{ promtail_location }}"
    mode: 0755

- name: Unarchive Promtail
  unarchive:
    src: "/tmp/promtail-linux.zip"
    dest: "{{ promtail_location }}"
    remote_src: yes
    mode: '0755'

- name: Create an Promtail config file
  template:
    src: promtail-config.yaml.j2
    dest: "{{ promtail_location }}/promtail-config.yaml"
    mode: 0644
    force: yes

- name: Create Promtail's Supervisor config file
  template:
    src: promtail.conf.j2
    dest: "/etc/supervisor/conf.d/promtail.conf"
    mode: 0644
    force: yes
